In [50]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/100 Days Of Data Engineering - Make A Copy And Use As You Need - Sheet1.csv")
df

,Unnamed: 0,100 Days Note,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,100 days is just a little over 3 months and I ...,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Day,Task,Notes,Category,Links,NaN,NaN,NaN
4,Day 1,"For day one, what I reccomend is taking the ti...",NaN,Take a moment to write your goals,https://discord.gg/2yRJq7Eg3k,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
99,Day 96,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
100,Day 97,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
101,Day 98,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
102,Day 99,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
103,Day 100,"Write a blog, post or create a github repo to ...",NaN,NaN,#REF!,NaN,NaN,NaN

In [53]:
df = df.rename(columns={'Unnamed: 0':'day','100 Days Note':'task','Unnamed: 2':'notes','Unnamed: 3':'category','Unnamed: 4':'LinkA','Unnamed: 5':'LinkB','Unnamed: 6':'LinkC','Unnamed: 7':'LinkD'})

In [67]:
df.keys()

Index(['day', 'task', 'notes', 'category', 'LinkA', 'LinkB', 'LinkC', 'LinkD'], dtype='object')

In [55]:
df = df[df["day"].str.contains("Day") == True]
df
df = df.drop([3])
df

,day,task,notes,category,LinkA,LinkB,LinkC,LinkD
4,Day 1,"For day one, what I reccomend is taking the ti...",NaN,Take a moment to write your goals,https://discord.gg/2yRJq7Eg3k,NaN,NaN,NaN
5,Day 2,1. Downloading SQL Server And Creating A Table...,NaN,SQL,https://www.youtube.com/watch?v=RSlqWnP-Dy8&li...,https://www.youtube.com/watch?v=9URM1_2S0ho&li...,https://www.youtube.com/watch?v=Twusw__OzA8&li...,https://www.interviewquery.com/learning-paths/...
6,Day 3,1. SQL Interview Tips\n2.Solving More Problems...,NaN,SQL,https://www.youtube.com/watch?v=W2L7Q3J-ei0&t=1s,https://www.youtube.com/watch?v=FNYdBLwZ6cE,NaN,NaN
7,Day 4,1. Partition By\n2. CTE (Common Table Expressi...,NaN,SQL,https://www.youtube.com/watch?v=D6XNlTfglW4&li...,https://www.youtube.com/watch?v=K1WeoKxLZ5o&li...,https://www.youtube.com/watch?v=NrBJmtD0kEw&li...,NaN
8,Day 5,1. Loops Strings And Tuples\n2. Functions\n3. ...,NaN,Programming,https://www.youtube.com/watch?v=iv5m0c-8Opc&li...,https://www.youtube.com/watch?v=8YbIwueDQx4&li...,https://www.youtube.com/watch?v=xwPWcFKeIac&li...,https://www.youtube.com/watch?v=BYpSfx7I6x4&li...
...,...,...,...,...,...,...,...,...
99,Day 96,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
100,Day 97,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
101,Day 98,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
102,Day 99,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
103,Day 100,"Write a blog, post or create a github repo to ...",NaN,NaN,#REF!,NaN,NaN,NaN

In [56]:
df

,day,task,notes,category,LinkA,LinkB,LinkC,LinkD
4,Day 1,"For day one, what I reccomend is taking the ti...",NaN,Take a moment to write your goals,https://discord.gg/2yRJq7Eg3k,NaN,NaN,NaN
5,Day 2,1. Downloading SQL Server And Creating A Table...,NaN,SQL,https://www.youtube.com/watch?v=RSlqWnP-Dy8&li...,https://www.youtube.com/watch?v=9URM1_2S0ho&li...,https://www.youtube.com/watch?v=Twusw__OzA8&li...,https://www.interviewquery.com/learning-paths/...
6,Day 3,1. SQL Interview Tips\n2.Solving More Problems...,NaN,SQL,https://www.youtube.com/watch?v=W2L7Q3J-ei0&t=1s,https://www.youtube.com/watch?v=FNYdBLwZ6cE,NaN,NaN
7,Day 4,1. Partition By\n2. CTE (Common Table Expressi...,NaN,SQL,https://www.youtube.com/watch?v=D6XNlTfglW4&li...,https://www.youtube.com/watch?v=K1WeoKxLZ5o&li...,https://www.youtube.com/watch?v=NrBJmtD0kEw&li...,NaN
8,Day 5,1. Loops Strings And Tuples\n2. Functions\n3. ...,NaN,Programming,https://www.youtube.com/watch?v=iv5m0c-8Opc&li...,https://www.youtube.com/watch?v=8YbIwueDQx4&li...,https://www.youtube.com/watch?v=xwPWcFKeIac&li...,https://www.youtube.com/watch?v=BYpSfx7I6x4&li...
...,...,...,...,...,...,...,...,...
99,Day 96,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
100,Day 97,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
101,Day 98,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
102,Day 99,NaN,NaN,NaN,#REF!,NaN,NaN,NaN
103,Day 100,"Write a blog, post or create a github repo to ...",NaN,NaN,#REF!,NaN,NaN,NaN

In [64]:
df = df.reset_index()
df = df.drop('index',axis=1)
df = df.replace(np.nan, None)

In [68]:
df.to_parquet('../data/task.parquet')

In [65]:
df.keys

<bound method NDFrame.keys of         day                                               task notes  \
0     Day 1  For day one, what I reccomend is taking the ti...  None
1     Day 2  1. Downloading SQL Server And Creating A Table...  None
2     Day 3  1. SQL Interview Tips\n2.Solving More Problems...  None
3     Day 4  1. Partition By\n2. CTE (Common Table Expressi...  None
4     Day 5  1. Loops Strings And Tuples\n2. Functions\n3. ...  None
..      ...                                                ...   ...
95   Day 96                                               None  None
96   Day 97                                               None  None
97   Day 98                                               None  None
98   Day 99                                               None  None
99  Day 100  Write a blog, post or create a github repo to ...  None

                             category  \
0   Take a moment to write your goals
1                                 SQL
2                                 SQL
3                                 SQL
4                         Programming
..                                ...
95                               None
96                               None
97                               None
98                               None
99                               None

                                                LinkA  \
0                       https://discord.gg/2yRJq7Eg3k
1   https://www.youtube.com/watch?v=RSlqWnP-Dy8&li...
2    https://www.youtube.com/watch?v=W2L7Q3J-ei0&t=1s
3   https://www.youtube.com/watch?v=D6XNlTfglW4&li...
4   https://www.youtube.com/watch?v=iv5m0c-8Opc&li...
..                                                ...
95                                              #REF!
96                                              #REF!
97                                              #REF!
98                                              #REF!
99                                              #REF!

                                                LinkB  \
0                                                None
1   https://www.youtube.com/watch?v=9URM1_2S0ho&li...
2         https://www.youtube.com/watch?v=FNYdBLwZ6cE
3   https://www.youtube.com/watch?v=K1WeoKxLZ5o&li...
4   https://www.youtube.com/watch?v=8YbIwueDQx4&li...
..                                                ...
95                                               None
96                                               None
97                                               None
98                                               None
99                                               None

                                                LinkC  \
0                                                None
1   https://www.youtube.com/watch?v=Twusw__OzA8&li...
2                                                None
3   https://www.youtube.com/watch?v=NrBJmtD0kEw&li...
4   https://www.youtube.com/watch?v=xwPWcFKeIac&li...
..                                                ...
95                                               None
96                                               None
97                                               None
98                                               None
99                                               None

                                                LinkD
0                                                None
1   https://www.interviewquery.com/learning-paths/...
2                                                None
3                                                None
4   https://www.youtube.com/watch?v=BYpSfx7I6x4&li...
..                                                ...
95                                               None
96                                               None
97                                               None
98                                               None
99                                               None

[100 rows x 8 columns]>